version: '2.2'

services:
  cli:
    image: azuracast/azuracast_testing:latest
    volumes:
      - ./:/app
      - composer_data:/tmp
    command: composer test

volumes:
  composer_data: {}
