name: Test Suite

on: [push, pull_request]

jobs:
  test_suite:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    
    - name: Run test suite
      uses: docker://azuracast/azuracast_testing:latest
