name: Test Suite

on:
  push :
  pull_request :
  workflow_dispatch :
jobs:
  test_suite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Test Image
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: azuracast/nowplaying:latest
          cache-from: type=gha,mode=max
          cache-to: type=gha,mode=max

      - name: Run CI Test Suite
        run: |
          docker-compose run --rm cli composer run ci
